org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.3
mod_version=0.1.0
mod_id=el_pack_manager
mod_name=eL Pack Manager
mod_group=com.elbano12.elpackmanager

fabric_loader_version=0.19.5
fabric_api_version=0.160.6+26.3

neoforge_version=26.3.0.10-beta
